<script lang="ts">
	import CodeBlock from '$lib/components/CodeBlock.svelte';

	const serviceExample = `# Install daemon as system service (auto-detects platform)
oxmgr service install --system auto

# Check service status
oxmgr service status --system auto

# Uninstall service
oxmgr service uninstall --system auto`;

	const systemdUnit = `# /etc/systemd/system/oxmgr.service (generated by oxmgr service install)
[Unit]
Description=Oxmgr Process Manager
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/usr/local/bin/oxmgr daemon start
ExecStop=/usr/local/bin/oxmgr daemon stop
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target`;
</script>

<svelte:head>
	<title>System Services — Oxmgr Docs</title>
	<meta name="description" content="Install the Oxmgr daemon as a system service for automatic startup on boot. Supports systemd on Linux, launchd on macOS, and Task Scheduler on Windows." />
	<link rel="canonical" href="https://oxmgr.empellio.com/docs/system-services" />
	<meta property="og:title" content="Oxmgr System Services" />
	<meta property="og:description" content="Boot persistence for Oxmgr: install as systemd, launchd, or Windows Task Scheduler service with a single command." />
	<meta property="og:url" content="https://oxmgr.empellio.com/docs/system-services" />
</svelte:head>

<div class="mb-10 sm:mb-12">
	<p class="section-label">Documentation</p>
	<h1 class="section-title text-3xl sm:text-4xl lg:text-5xl mb-4">System Services</h1>
	<p class="text-zinc-400 text-base sm:text-lg leading-relaxed max-w-2xl">
		Install the Oxmgr daemon as a system service so it starts automatically on boot.
		<code class="code-inline">--system auto</code> detects your platform.
	</p>
</div>

<div class="space-y-10">

	<div>
		<h2 class="doc-heading">Install as a System Service</h2>
		<CodeBlock code={serviceExample} language="bash" />

		<div class="mt-6 grid sm:grid-cols-3 gap-3">
			{#each [
				{ platform: 'Linux', system: 'systemd', icon: '🐧', detail: 'Creates a .service unit file in /etc/systemd/system' },
				{ platform: 'macOS', system: 'launchd', icon: '🍎', detail: 'Creates a .plist in /Library/LaunchDaemons' },
				{ platform: 'Windows', system: 'Task Scheduler', icon: '🪟', detail: 'Registers a scheduled task for boot startup' }
			] as item}
				<div class="border border-zinc-800 rounded bg-zinc-900/30 px-4 py-4">
					<p class="text-2xl mb-2">{item.icon}</p>
					<p class="text-sm font-semibold text-zinc-300">{item.platform}</p>
					<p class="text-xs font-mono text-zinc-500 mt-1 mb-2">{item.system}</p>
					<p class="text-xs text-zinc-600">{item.detail}</p>
				</div>
			{/each}
		</div>
	</div>

	<div>
		<h2 class="doc-heading">Verify Daemon Health</h2>
		<CodeBlock code={`# Run oxmgr doctor to check daemon health\noxmgr doctor`} language="bash" />
		<p class="doc-text mt-3">
			<code class="code-inline">oxmgr doctor</code> checks that the daemon is running, the API is reachable,
			and the data directory is accessible.
		</p>
	</div>

	<div>
		<h2 class="doc-heading">Generated systemd Unit (Linux)</h2>
		<p class="doc-text mb-4">
			This is what <code class="code-inline">oxmgr service install --system auto</code> generates on Linux.
			You can also write this manually if you prefer:
		</p>
		<CodeBlock code={systemdUnit} language="ini" filename="/etc/systemd/system/oxmgr.service" />
		<CodeBlock code={`sudo systemctl daemon-reload\nsudo systemctl enable oxmgr\nsudo systemctl start oxmgr\n\n# Check status\nsudo systemctl status oxmgr\njournalctl -u oxmgr -f`} language="bash" />
	</div>

	<div class="border border-zinc-800/70 rounded bg-zinc-900/30 px-5 py-4">
		<h3 class="text-sm font-semibold text-zinc-300 mb-2">User vs system service</h3>
		<p class="doc-text">
			The <code class="code-inline">--system auto</code> flag installs a system-wide service (requires root on Linux/macOS).
			For user-scoped install (starts on user login, not boot), the daemon can also be run as a user service via
			<code class="code-inline">systemctl --user</code> on Linux. Pass the systemd unit file manually in that case.
		</p>
	</div>

</div>

<!-- Footer CTA -->
<div class="mt-16 border border-zinc-800 rounded bg-zinc-900/30 p-6">
	<div class="flex flex-col sm:flex-row items-start sm:items-center gap-4">
		<div class="flex-1">
			<h3 class="font-semibold text-white mb-1">Still have questions?</h3>
			<p class="text-zinc-400 text-sm">Open an issue or browse the source on GitHub.</p>
		</div>
		<a
			href="https://github.com/Vladimir-Urik/OxMgr/issues"
			target="_blank"
			rel="noopener noreferrer"
			class="btn-primary text-sm shrink-0"
		>
			Open an Issue ↗
		</a>
	</div>
</div>
